DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS contact;

create table company
(
    id   bigint generated by default as identity,
    name varchar(200) not null,
    constraint pk_company primary key (id)
);

create table contact
(
    id   bigint generated by default as identity,
    first_name varchar(200) not null,
    last_name varchar(200) not null,
    email text not null UNIQUE ,
    phone_number varchar(30),
    company_id INTEGER REFERENCES company(id),
    status text not null,
    comment text,
    creation_date TIMESTAMP WITHOUT TIME ZONE,
    last_updated_date TIMESTAMP WITHOUT TIME ZONE,
    constraint pk_contact primary key (id)
    --constraint fk_company_id foreign key  (company) REFERENCES company(id)
);


insert into company (name)
values ('Company #1'),
       ('Company #2'),
       ('Company #3');

insert into contact (first_name, last_name, email, phone_number, company_id, status, comment, creation_date, last_updated_date)
values (
        'Mátyás',
        'Hunyadi',
        'mátyás@king.com',
        '0630555555',
        3,
        'ACTIVE',
        'no comment',
        '2021-09-24 19:10:25-07',
        '2021-09-24 19:10:25-07');

insert into contact (first_name, last_name, email, phone_number, company_id, status, comment, creation_date, last_updated_date)
values (
           'Aatteo',
           'Corvini',
           'matteo@king.com',
           '0630555555',
           3,
           'ACTIVE',
           'no comment',
           '2021-09-24 19:10:25-07',
           '2021-09-24 19:10:25-07');

insert into contact (first_name, last_name, email, phone_number, company_id, status, comment, creation_date, last_updated_date)
values (
           'INACTIVE',
           'USER',
           'inactive@user.com',
           '0630555555',
           1,
           'DELETED',
           'no comment',
           '2021-09-25 09:10:25-07',
           '2021-09-25 09:10:25-07');